version: '3'
services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $PG_PASS
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
  webapp:
    restart: always
    build:
      context: .
    container_name: self_manage_sys
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4400 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASS
    volumes:
      - .:/webapp
      - bundle:/usr/local/bundle
    ports:
      - 4400:4400
    stdin_open: true
    tty: true
    depends_on:
      - db
volumes:
  postgres_volume:
  bundle:
    driver: local
